# Generated by Django 5.1 on 2024-08-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_experience_jobpost_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
