# Generated by Django 5.1 on 2024-08-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_username_profile_user_jobposting_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobPosting',
            new_name='JobPost',
        ),
    ]
